services:
    zookeeper:
        image: bitnamilegacy/zookeeper:3.8.1
        restart: always
        ports:
          - "2181:2181"
        volumes:
          - zookeeper_data:/bitnami
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes         
          
    kafka:
        image: bitnamilegacy/kafka:3.5.1
        container_name: kafka
        ports:
          - "9092:9092"
        restart: always
        volumes:
          - "kafka_data:/bitnami"
        environment:
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
          - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
          - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        depends_on:
          - zookeeper
      
    mongo-container:
        container_name: mongo-container
        image: mongo:latest
        restart: always
        ports:
          - "27017:27017"
        volumes:
          - mongodb_data_container:/data/db
          
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Password123"
          MSSQL_PID: "Express"
        ports:
          - "1433:1433"
        restart: always
        
    post-cmd-api:
        build:
          context: .
          dockerfile: src/Post.Cmd/Post.Cmd.Api/Dockerfile
        container_name: post-cmd-api
        ports:
          - "8080:8080"
          - "8081:8081"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - MongoDbConfig__ConnectionString=mongodb://mongo-container:27017
          - MongoDbConfig__Database=socialMedia
          - MongoDbConfig__Collection=eventStore
          - ProducerConfig__BootstrapServers=kafka:29092
        depends_on:
          - mongo-container
          - kafka

volumes:
      zookeeper_data:
        driver: local
      kafka_data:
        driver: local
      mongodb_data_container:
        driver: local
   
networks:
      default:    
        name: smpost
        external: true
    
