<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>a588c5a7-645f-481d-9da9-0e94bed5e933</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\CQRS.Core\CQRS.Core.csproj" />
		<ProjectReference Include="..\..\Post.Common\Post.Common.csproj" />
		<ProjectReference Include="..\Post.Query.Domain\Post.Query.Domain.csproj" />
		<ProjectReference Include="..\Post.Query.Infrastructure\Post.Query.Infrastructure.csproj" />
	</ItemGroup>

</Project>
